version: 1.0.{build}
image: Visual Studio 2017 Preview
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
build_script:
  - dotnet build ./src -c Release
test_script:
- ps: >-
    dotnet test ${workspaceFolder}/src/Justine.NUnit.Tests /p:CollectCoverage=true /p:Include=\"[Justine*]*\" /p:Exclude=\"[NUnit3.TestAdapter*]*\" /p:CoverletOutputFormat=opencover /p:Threshold=100 /p:ThresholdType=line

    nuget install OpenCover -OutputDirectory packages -Version 4.6.519

    dotnet tool install coveralls.net --version 1.0.0 --tool-path tools

    $coveralls = ".\tools\csmacnz.coveralls.exe"

    & $coveralls --opencover -i ./src/Justine.xUnit.Tests/coverage.opencover.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
